### PR TITLE
refactor: remove all c style casts in univalue subtree

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
A part of https://github.com/bitcoin/bitcoin/pull/23810

### CODE REVIEW

**Comment by maflcko** [comment]
-0. It would be safer to use C++11 braced inits for all of those

**Comment by PastaPastaPasta** [comment]
I have replaced static_casts with braced inits where possible, but it's not always possible as narrowing conversions aren't allowed and require explicit static_cast

**Comment by PastaPastaPasta** [comment]
@MarcoFalke could you please review the current state of this PR?

**Comment by maflcko** [comment]
second commit lgtm, but not sure about the first one

**Comment by maflcko** [comment]
Closing for now due to inactivity. Let me know when you want to work on this again. As I mentioned, the second commit should be fine.

**Pull request closed without merging**
